# Generated by Django 4.1.7 on 2023-03-19 07:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handbook_name', models.CharField(choices=[('VM', 'Модель техники'), ('EM', 'Модель двигателя'), ('TM', 'Модель трансмиссии'), ('MA', 'Модель ведущего моста'), ('DA', 'Модель управляемого моста'), ('MT', 'Вид ТО'), ('FN', 'Узел отказа'), ('RD', 'Способ восстановления'), ('SC', 'Сервисная компания')], max_length=2)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True, verbose_name='зав. № машины')),
                ('engine_id', models.CharField(max_length=20, verbose_name='Зав. № двигателя')),
                ('transmission_id', models.CharField(max_length=20, verbose_name='Зав. № трансмиссии')),
                ('main_axle_id', models.CharField(max_length=20, verbose_name='Зав. № ведущего моста')),
                ('driven_axle_id', models.CharField(max_length=20, verbose_name='Зав. № управляемого моста')),
                ('contract_id_date', models.CharField(blank=True, max_length=20, verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(default=datetime.date.today, verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=100, verbose_name='Грузополучатель (конечный потребитель)')),
                ('shipping_address', models.CharField(max_length=100, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(default='Стандарт', verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driven_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_axle_model', to='api.handbook', verbose_name='Модель управляемого моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='api.handbook', verbose_name='Модель двигателя')),
                ('main_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_axle_model', to='api.handbook', verbose_name='Модель ведущего моста')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='api.handbook', verbose_name='Модель трансмиссии')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_model', to='api.handbook', verbose_name='Модель техники')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(default=datetime.date.today, verbose_name='Дата отказа')),
                ('operating_time', models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('repair_date', models.DateField(default=datetime.date.today, verbose_name='Дата восстановления')),
                ('downtime', models.PositiveIntegerField(default=0, verbose_name='Время простоя техники')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_node', to='api.handbook', verbose_name='Узел отказа')),
                ('repair_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_description', to='api.handbook', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle', verbose_name='Машина')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(default=datetime.date.today, verbose_name='Дата проведения ТО')),
                ('operating_time', models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')),
                ('work_order_id', models.CharField(max_length=30, verbose_name='Номер заказ-наряда')),
                ('work_order_date', models.DateField(default=datetime.date.today, verbose_name='Дата заказ-наряда')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='api.handbook', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle', verbose_name='Машина')),
            ],
        ),
    ]
